[server]
fileWatcherType = "none"
headless = true

[browser]
gatherUsageStats = false

[theme]
base = "dark"
primaryColor = "#FFFFFF"
backgroundColor = "#09090B"
secondaryBackgroundColor = "#18181B"
textColor = "#FAFAFA"
font = "sans serif"
